### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by erebor** [probablycorey/coffee-eval#7]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
Object.activate (/Users/rew/.atom/packages/coffee-eval/lib/coffee-eval.coffee:9:9)
```

**Comment by probablycorey** [comment]
Sorry, I'm no longer maintaining this package. I'm using the [script](https://atom.io/packages/script) package as a replacement.
